# Generated by Django 4.0.2 on 2023-05-08 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stress', models.FloatField(verbose_name='ストレス')),
                ('happy', models.FloatField(verbose_name='ハッピー')),
                ('energy', models.FloatField(verbose_name='エネルギー')),
                ('astray', models.FloatField(verbose_name='人生に迷った')),
                ('tired', models.FloatField(verbose_name='疲れた')),
                ('adventure', models.FloatField(verbose_name='冒険')),
                ('nature', models.FloatField(verbose_name='自然')),
                ('architecture', models.FloatField(verbose_name='建築物')),
                ('healing', models.FloatField(verbose_name='癒し')),
                ('instagram', models.FloatField(verbose_name='インスタ映え')),
                ('girls', models.FloatField(verbose_name='女子旅')),
                ('food', models.FloatField(verbose_name='料理')),
                ('art', models.FloatField(verbose_name='芸術')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50, verbose_name='国名')),
                ('language1', models.CharField(max_length=50, verbose_name='言語1')),
                ('language2', models.CharField(blank=True, max_length=50, null=True, verbose_name='言語2')),
                ('language3', models.CharField(blank=True, max_length=50, null=True, verbose_name='言語3')),
                ('religion1', models.CharField(max_length=50, verbose_name='宗教1')),
                ('religion2', models.CharField(blank=True, max_length=50, null=True, verbose_name='宗教2')),
                ('religion3', models.CharField(blank=True, max_length=50, null=True, verbose_name='宗教3')),
                ('comment', models.TextField(verbose_name='コメント')),
                ('image', models.ImageField(upload_to='country_photos', verbose_name='イメージ')),
                ('map', models.TextField(verbose_name='Google_MAP')),
                ('flight', models.TextField(blank=True, null=True, verbose_name='skyscanner')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('comment', models.TextField(verbose_name='コメント')),
                ('itinerary', models.TextField(verbose_name='旅程')),
                ('days1', models.IntegerField(verbose_name='最短日程')),
                ('days2', models.IntegerField(verbose_name='最長日程')),
                ('season1', models.IntegerField(verbose_name='時期1')),
                ('season2', models.IntegerField(verbose_name='時期2')),
                ('image1', models.ImageField(upload_to='post_photos', verbose_name='イメージ1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='post_photos', verbose_name='イメージ2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='post_photos', verbose_name='イメージ3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='post_photos', verbose_name='イメージ4')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='変更日時')),
                ('attribute', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='photo.attribute', verbose_name='属性')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='photo.country', verbose_name='国')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='photo.country', verbose_name='国'),
        ),
    ]
